// Generated by Scripts/auction/roster.py from Scripts/auction/Teams.csv. Do not edit. Franchise order is table order.
static const TCHAR* TeamRows[] =
{
	TEXT("Code,Name,Short,City,Home,Owner,Captain2026,HeadCoach2026,PrimaryHex,SecondaryHex,Titles"),
	TEXT("CSK,Chennai Super Kings,SUPER KINGS,Chennai,MA Chidambaram Stadium,Chennai Super Kings Cricket Ltd,Ruturaj Gaikwad,Stephen Fleming,#F9CD05,#0B4EA2,5"),
	TEXT("MI,Mumbai Indians,INDIANS,Mumbai,Wankhede Stadium,Reliance Industries,Hardik Pandya,Mahela Jayawardene,#004BA0,#D1AB3E,5"),
	TEXT("RCB,Royal Challengers Bengaluru,ROYAL CHALLENGERS,Bengaluru,M Chinnaswamy Stadium,Aditya Birla Group-led consortium (Times Group/Bolt Ventures/Blackstone),Rajat Patidar,Andy Flower,#D6121F,#1A1A1A,2"),
	TEXT("KKR,Kolkata Knight Riders,KNIGHT RIDERS,Kolkata,Eden Gardens,Knight Riders Group (Shah Rukh Khan/Mehta Group),Ajinkya Rahane,Abhishek Nayar,#3A225D,#B3A123,3"),
	TEXT("SRH,Sunrisers Hyderabad,SUNRISERS,Hyderabad,Rajiv Gandhi International Stadium,Sun Group,Pat Cummins,Daniel Vettori,#F26522,#1A1A1A,1"),
	TEXT("DC,Delhi Capitals,CAPITALS,Delhi,Arun Jaitley Stadium,JSW Sports and GMR Sports,Axar Patel,Hemang Badani,#17479E,#EF1B23,0"),
	TEXT("PBKS,Punjab Kings,KINGS,New Chandigarh,Maharaja Yadavindra Singh Stadium,KPH Dream Cricket (Mohit Burman/Ness Wadia/Preity Zinta/Karan Paul),Shreyas Iyer,Ricky Ponting,#DD1F2D,#A7A9AC,0"),
	TEXT("RR,Rajasthan Royals,ROYALS,Jaipur,Sawai Mansingh Stadium,Lakshmi Mittal (majority) with Adar Poonawalla and Manoj Badale,Riyan Parag,Kumar Sangakkara,#EA1A85,#254AA5,1"),
	TEXT("GT,Gujarat Titans,TITANS,Ahmedabad,Narendra Modi Stadium,Torrent Group (67%) and CVC Capital Partners (33%),Shubman Gill,Ashish Nehra,#1B2A4A,#DBBE6E,1"),
	TEXT("LSG,Lucknow Super Giants,SUPER GIANTS,Lucknow,Ekana Cricket Stadium,RP-Sanjiv Goenka Group,Rishabh Pant,Justin Langer,#0A4FA8,#F58220,0"),
};
