#!/usr/bin/env python3
"""Compiles Scripts/auction/Players.csv and Teams.csv into Source/CRICKET26/Auction/AuctionRoster.inl and
AuctionTeams.inl, so the roster and the franchises ship inside the binary (Content/ is not versioned).
Usage: Scripts/auction/roster.py [Players.csv [Teams.csv]]"""
import csv, io, sys, unicodedata
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SRC = Path(sys.argv[1]) if len(sys.argv) > 1 else ROOT / "Scripts/auction/Players.csv"
TEAMS = Path(sys.argv[2]) if len(sys.argv) > 2 else ROOT / "Scripts/auction/Teams.csv"
OUT = ROOT / "Source/CRICKET26/Auction/AuctionRoster.inl"
TEAMS_OUT = ROOT / "Source/CRICKET26/Auction/AuctionTeams.inl"


def ascii_cell(s):
    s = unicodedata.normalize("NFKD", s).encode("ascii", "ignore").decode()
    return s.replace(",", " ").replace('"', "").replace("\\", "").strip()


def compile_csv(src, out, name, generator_note):
    rows = list(csv.reader(io.open(src, encoding="utf-8-sig")))
    header, body = rows[0], [r for r in rows[1:] if any(c.strip() for c in r)]
    assert "Name" in header, f"{src.name} needs a header row with a Name column"
    lines = [f"// Generated by Scripts/auction/roster.py from Scripts/auction/{src.name}. Do not edit.{generator_note}",
             f"static const TCHAR* {name}[] =", "{"]
    for r in [header] + body:
        lines.append('\tTEXT("%s"),' % ",".join(ascii_cell(c) for c in r))
    lines.append("};")
    out.write_text("\n".join(lines) + "\n")
    return len(body)


n = compile_csv(SRC, OUT, "RosterRows", "")
t = compile_csv(TEAMS, TEAMS_OUT, "TeamRows", " Franchise order is table order.")
print(f"{n} players -> {OUT.relative_to(ROOT)}")
print(f"{t} franchises -> {TEAMS_OUT.relative_to(ROOT)}")
