#!/usr/bin/env python3
"""Compiles Scripts/auction/Players.csv into Source/CRICKET26/Auction/AuctionRoster.inl, so the roster ships
inside the binary (Content/ is not versioned). Usage: Scripts/auction/roster.py [Players.csv]"""
import csv, io, sys, unicodedata
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SRC = Path(sys.argv[1]) if len(sys.argv) > 1 else ROOT / "Scripts/auction/Players.csv"
OUT = ROOT / "Source/CRICKET26/Auction/AuctionRoster.inl"


def ascii_cell(s):
    s = unicodedata.normalize("NFKD", s).encode("ascii", "ignore").decode()
    return s.replace(",", " ").replace('"', "").replace("\\", "").strip()


rows = list(csv.reader(io.open(SRC, encoding="utf-8-sig")))
header, body = rows[0], [r for r in rows[1:] if any(c.strip() for c in r)]
assert "Name" in header, "Players.csv needs a header row with a Name column"
lines = ["// Generated by Scripts/auction/roster.py from Scripts/auction/Players.csv. Do not edit.",
         "static const TCHAR* RosterRows[] =", "{"]
for r in [header] + body:
    lines.append('\tTEXT("%s"),' % ",".join(ascii_cell(c) for c in r))
lines.append("};")
OUT.write_text("\n".join(lines) + "\n")
print(f"{len(body)} players -> {OUT.relative_to(ROOT)}")
